"""reminder markers

Revision ID: 002
Revises: 001
Create Date: 2025-07-03 14:14:29.995370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('notified_one_day', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('meetings', sa.Column('notified_two_hours', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'notified_two_hours')
    op.drop_column('meetings', 'notified_one_day')
    # ### end Alembic commands ###
